import { test } from 'node:test';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { configurePi } from '../src/pi/tui-executor.js';
import { startPiChat, sendPiChatPrompt, piChatSnapshot, subscribePiChat, respondPiChatUi, stopPiChatAndWait, isPiChatRunning } from '../src/pi/chat-executor.js';

test('RPC acceptance, live snapshot watermark, UI response and writer teardown', async t => {
  configurePi({ cliEntry: fileURLToPath(new URL('./fixtures/pi-rpc.fixture.mjs', import.meta.url)) });
  const record = await startPiChat({ taskId: 'test', childSessionId: 'one', sessionFile: '/tmp/unused-pi-test.jsonl', workingDir: process.cwd() });
  t.after(async () => { await stopPiChatAndWait('test', 'one'); configurePi(); });
  const frames = [];
  const unsubscribe = subscribePiChat('test', 'one', frame => frames.push(frame));
  t.after(unsubscribe);
  const response = await sendPiChatPrompt('test', 'one', 'hello', { mode: 'queue' });
  assert.equal(response.success, true);
  const snapshot = await piChatSnapshot('test', 'one');
  assert.deepEqual(snapshot.messages.map(message => message.content), ['history']);
  assert.equal(snapshot.live.content[0].text, 'followUp');
  assert.ok(snapshot.sequence >= frames.find(frame => frame.type === 'chat_ui_request').sequence);
  assert.deepEqual(snapshot.requests[0].options, ['Allow', 'Block']);
  assert.equal(respondPiChatUi('test', 'one', { id: 'select-1', value: 'Allow' }), true);
  assert.equal(respondPiChatUi('test', 'one', { id: 'select-1', value: 'Block' }), false);
  assert.ok(frames.some(frame => frame.type === 'chat_ui_resolved'));
  assert.equal((await sendPiChatPrompt('test', 'one', 'guide', { mode: 'steer' })).success, true);
  assert.equal((await piChatSnapshot('test', 'one')).live.content[0].text, 'steer');
  await assert.rejects(sendPiChatPrompt('test', 'one', 'bad', { mode: 'invalid' }), /发送方式/);
  await assert.rejects(sendPiChatPrompt('test', 'one', 'bad', { images: [{ type: 'image', data: 'invalid!', mimeType: 'image/png' }] }), /图片/);
  await stopPiChatAndWait('test', 'one');
  assert.equal(isPiChatRunning('test', 'one'), false);
  assert.equal(record.exited, true);
});
